### ISSUE TITLE
HostListener not attaching listener

### ISSUE THREAD

**Issue by jonlighthill** [thisissoon/angular-infinite-scroll#12]
I had to modify the code to get this to actually work. Instead of using the events file i am just listening to the window scroll event and grabbing the following properties

    @HostListener('window:scroll', ['$event'])
    public onScroll(): void {
        const height = document.documentElement.scrollHeight;
        const y = window.scrollY + window.pageYOffset;
        this.scroll$.next({ y, height });
    }

**Comment by jamesjwarren** [comment]
Hi, it sounds like you're trying to use the directive on a non-scrollable element which is not emitting a scroll event and thus having to fallback to using the window scroll event. This directive is designed to work on any scrollable element and listen for scroll events from that target element rather than the window itself, we've found this to be more flexible.
